### ISSUE TITLE
Grammar converter bug

### ISSUE THREAD

**Issue by benajibayassine** [RobMcH/CYK-Parser#2]
the grammar converter has a bug when a rule has more than 3 elements on the right hand side of the rule.

for example, this:
S -> A B C D M

converts to: 
[['S', 'S2', 'MODEL'], ['S0', 'A', 'B', 'S1', 'S0', 'C', 'S2', 'S1', 'D'], ['A', "'I'"], ['B', "'w'"], ['D', "'d'"], ['C', "'l'"], ['M', "'m'"]]

**Comment by RobMcH** [comment]
Solved in latest commit.
