### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by tyilo** [RobMcH/CYK-Parser#3]
Using the following grammar `B C` is not recognised:
```
S -> A
B -> 'B'
C -> 'C'
A -> B C
```

Moving `A -> B C` up seems to fix it:
```
S -> A
A -> B C
B -> 'B'
C -> 'C'
```

This is obviously a bug.

**Comment by RobMcH** [comment]
Thanks for reporting this. The latest commit should fix this behaviour!
